services:
  db:
    image: postgis/postgis:14-3.3
    container_name: postgis_db
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Wait for database to be fully ready
    env_file:
      - .env
    environment:
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db  # Set to service name
      DATABASE_PORT: 5432
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "until pg_isready -h db -p 5432 -U ${DATABASE_USER}; do sleep 5; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pg_data:
